# main
trigger:
- az_templates

pool:
  vmImage: windows-latest

pr:
 branches:
   include:
     - az_templates
    #  - main
   exclude:
     - az_templates



stages:
  - stage: 'UT'
    displayName: 'Unit Test Stage'
    jobs:
      - job: 'unitTest'
        displayName: 'Running Unit Tests'
        steps:
          - template: start.yml
            
  - stage: 'Build'
    displayName: 'build the script'
    jobs:
      - job: 'buildscript'
        displayName: 'building a script'
        steps:
          -  script: echo 'Running a demo app unit test'
            # displayName: 'Echo Message'

          - task: UsePythonVersion@0
            inputs:
              versionSpec: '3.x'
              addToPath: true
              architecture: 'x64'
            displayName: 'Set Python Version'
 