# main
trigger:
- test
pool:
  vmImage: windows-latest


jobs:
  - job: 'AzFunctionApp'
    displayName: 'connect to the az function app'
    steps:
    - task: ArchiveFiles@2
      inputs:
        rootFolderOrFile: '$(Build.SourcesDirectory)'
        includeRootFolder: false
        archiveType: 'zip'
        archiveFile: '$(Build.ArtifactStagingDirectory)/azfnapp1.zip'
        replaceExistingArchive: true
      displayName: 'Zip function app code'

    # Step 2: Publish the zip file as an artifact
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)/azfnapp1.zip'
        ArtifactName: 'drop'
        publishLocation: 'Container'
      displayName: 'Publish artifact'
    - task: AzureFunctionApp@1
      inputs:
        azureSubscription: 'Azure-DSE-APJ-BBL(17c6c273-d4ca-491d-bee5-d1b32f654eb3)'
        appType: 'functionAppLinux'
        appName: 'tf-fa'
        package: '$(Build.ArtifactStagingDirectory)/azfnapp1.zip'
        runtimeStack: 'PYTHON|3.10'
        
    # - task: AzureFunctionApp@2
    #   inputs:
    #     connectedServiceNameARM: 'Azure-DSE-APJ-BBL(17c6c273-d4ca-491d-bee5-d1b32f654eb3)'
    #     appType: 'functionAppLinux'
    #     appName: 'opscenter-data'
    #     package: '$(System.DefaultWorkingDirectory)/azfnapp2.zip'
    #     runtimeStack: 'PYTHON|3.10'
    #     deploymentMethod: 'auto'


                    
# steps:
# - script: echo Hello, world!
#   displayName: 'Run a one-line script'

# - script: |
#     echo Add other tasks to build, test, and deploy your project.
#     echo See https://aka.ms/yaml
#   displayName: 'Run a multi-line script'
