# File: start.yml

parameters:
  - name: buildSteps
    type: stepList
    default: []
stages:
  - stage: secure_buildstage
    pool:
      vmImage: windows-latest
    jobs:
      - job: secure_buildjob
        steps:
          - script: echo This happens before code
            displayName: 'Base: Pre-build'
          - script: echo Building
            displayName: 'Base: Build'

          - ${{ each step in parameters.buildSteps }}:
            - ${{ each pair in step }}:
                ${{ if ne(pair.value, 'CmdLine@2') }}:
                  ${{ pair.key }}: ${{ pair.value }}       
                ${{ if eq(pair.value, 'CmdLine@2') }}: 
                  # Step is rejected by raising a YAML syntax error: Unexpected value 'CmdLine@2'
                  ${{ pair.value }}: error         

          - script: echo This happens after code
            displayName: 'Base: Signing'


# steps:
# - script: echo 'Running a demo app unit test'
#   displayName: 'Echo Message'

# - task: UsePythonVersion@0
#   inputs:
#     versionSpec: '3.x'
#     addToPath: true
#     architecture: 'x64'
#   displayName: 'Set Python Version'
